<?php
// $Id$
/**
* Permisos
* @return array An array of valid permissions for the mapibar module
*/
function mapibar_permission() {
  return array('administer mapibar' => array(
      'title' => t('Administer values for Mapibar'),
   ));
} // function mapibar_perm()
/**
* Muestra el menú y llama al Admin
* @return array 
*/
function mapibar_menu() {
  $items = array();
  
  $items['admin/mapitravel'] = array(
    'title' => 'Machupicchu',
    'description' => 'All modules for Machupicchu Travel',
    'position' => 'right',
    'weight' => 0,
    'access arguments' => array('access administration pages'),
  );
  $items['admin/mapitravel/mapibar'] = array(
    'title' => 'MapiBar',
    'description' => 'Config values for Mapibar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapibar_admin'),
    'access arguments' => array('access administration pages'),
   );
  
  return $items;
} // function mapibar_menu()
/**
* Init
*/
function mapibar_init() {
  	$path = drupal_get_path('module', 'mapibar');
    drupal_add_css($path .'/mapibar.css');
    drupal_add_js($path .'/mapibar.js');
    if ($setting = variable_get('mapibar_width', 960)) {
      drupal_add_js(array('mapibar' => array('width' => $setting)), 'setting');
    }
	if ($setting = variable_get('mapibar_chat', 'http://media.perunoticias.net/html/machupicchu.html')) {
      drupal_add_js(array('mapibar' => array('chat' => $setting)), 'setting');
    }
	if ($setting = variable_get('mapibar_skype', 'http://media.perunoticias.net/html/skype.html')) {
      drupal_add_js(array('mapibar' => array('skype' => $setting)), 'setting');
    }
} // function mapibar_init()
/**
* Página de Administración de MapiBar
* @return array El Formulario
*/
function mapibar_admin() {
  $form = array();
  $form['mapibar_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Main e-mail'),
    '#size' => 30,
	'#default_value' => variable_get('mapibar_mail', 'info@machupicchu.biz'),
    '#maxlength' => 100,
    '#description' => t("This value appears in the contact bar."),
    '#required' => TRUE,
  );
  
  $form['mapibar_chat'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Chat window '),
    '#size' => 60,
	'#default_value' => variable_get('mapibar_chat', 'http://media.perunoticias.net/html/machupicchu.html'),
    '#maxlength' => 300,
    '#required' => TRUE,
  );
  
  $form['mapibar_skype'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Skype window'),
    '#size' => 60,
	'#default_value' => variable_get('mapibar_skype', 'http://media.perunoticias.net/html/skype.html'),
    '#maxlength' => 300,
    '#required' => TRUE,
  );
  
  $form['mapibar_width'] = array(
    '#type' => 'textfield',
    '#title' => t('The bar width in px'),
    '#size' => 10,
	'#default_value' => variable_get('mapibar_width', 960),
    '#maxlength' => 4,
    '#required' => TRUE,
  );
  
  return system_settings_form($form);
} // function mapibar_admin()
function mapibar_page_build(&$page) {
	global $language;
	$output = '
		<div id="contact-bar"> 
		  <ul> 
			<li id="cb-chat"> 
			  <div> ' . t('Chat with us<br /> 24/7') . ' </div>
			</li> 
			<li id="cb-mail"> <span>' . t('Book 24 hours') . '</span><br /> ';
			  $output .= variable_get('mapibar_mail', 'info@machupicchu.biz');
			  $output .= '<br /> 
			  machupicchutravel@hotmail.com </li> 
			<li id="cb-call"> <span>' . t('Book 24 hours') . '</span><br /> 
			  +0051-84-264242<br /> 
			  +0051-84-223010 </li> 
			<li id="cb-skype"> ' . t('Call us for FREE<br /> 24/7') . '</li> 
			<li id="cb-langs" class="idiomas last">';
			
			switch($language->language) {
				case 'es':
					$output .= '<em class="ban_en"><a href="http://www.machupicchutravelagency.com/">' . t('English') . '</a></em><br /> 
					<em class="ban_br"><a href="http://brasil.machupicchu.biz/">' . t('Portuguese') . '</a></em>';
				break;
				case 'en':
					$output .= '<em class="ban_br"><a href="http://brasil.machupicchu.biz/">' . t('Portuguese') . '</a></em> 
					<em class="ban_es"><a href="http://www.machupicchu.biz/">' . t('Spanish') . '</a></em>';
				break;
				default:
				$output .= '<em class="ban_en"><a href="http://www.machupicchutravelagency.com/">' . t('English') . '</a></em><br /> 
					<em class="ban_es"><a href="http://www.machupicchu.biz/">' . t('Spanish') . '</a></em>';
			}
			$output .= '</li> 
		  </ul> 
		</div>';
		
		$page['page_bottom']['mapibar'] = array(
			'#type' => 'markup',
			'#markup' => $output
		);
} // function mapibar_page_build()