<?php

/**
 * The current theme path 
 */
define('MAPIBAR_THEME_PATH', '/' . drupal_get_path('theme', variable_get('theme_default', NULL)));
define('MAPIBAR_MODULE_PATH', '/sites/all/modules/mapibar');

/**
 * Ancho de la barra
 */
define('MAPIBAR_WIDTH', 960);

/**
 * Ventana de Chat
 */
define('MAPIBAR_CHAT', MAPIBAR_THEME_PATH . '/chats/chat.php');

/**
 * Ventana de Skype
 */
define('MAPIBAR_SKYPE', MAPIBAR_THEME_PATH . '/chats/skype.php');

/**
 * Ventana de Llamada
 */
define('MAPIBAR_CALL', MAPIBAR_MODULE_PATH . '/static/llamada.php');

/**
 * Emails
 */
define('MAPIBAR_MAIL', 'info@machupicchu.biz,machupicchutravel@hotmail.com');

/**
 * Phones
 */
define('MAPIBAR_PHONES', '+0051-84-264242,+0051-84-223010');

/**
* Permisos
* @return array An array of valid permissions for the mapibar module
*/
function mapibar_permission() {
  return array('administer mapibar' => array(
      'title' => t('Administer values for Mapibar'),
   ));
} // function mapibar_perm()
/**
* Muestra el menú y llama al Admin
* @return array 
*/
function mapibar_menu() {
  $items = array();
  
  $items['admin/mapitravel'] = array(
    'title' => 'Machupicchu',
    'description' => 'All modules for Machupicchu Travel',
    'position' => 'right',
    'weight' => 0,
    'access arguments' => array('access administration pages'),
  );
  $items['admin/mapitravel/mapibar'] = array(
    'title' => 'MapiBar',
    'description' => 'Config values for Mapibar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapibar_admin'),
    'access arguments' => array('access administration pages'),
   );
  
  return $items;
} // function mapibar_menu()
/**
* Init
*/
function mapibar_init() {
    $path = drupal_get_path('module', 'mapibar');
    drupal_add_css($path .'/mapibar.css');
    drupal_add_js($path .'/mapibar.js');
    if ($setting = variable_get('mapibar_width', MAPIBAR_WIDTH)) {
      drupal_add_js(array('mapibar' => array('width' => $setting)), 'setting');
    }
    if ($setting = variable_get('mapibar_chat', MAPIBAR_CHAT)) {
      drupal_add_js(array('mapibar' => array('chat' => $setting)), 'setting');
    }
    if ($setting = variable_get('mapibar_skype', MAPIBAR_SKYPE)) {
      drupal_add_js(array('mapibar' => array('skype' => $setting)), 'setting');
    }
    if ($setting = variable_get('mapibar_call', MAPIBAR_CALL)) {
      drupal_add_js(array('mapibar' => array('call' => $setting)), 'setting');
    }
} // function mapibar_init()
/**
* Página de Administración de MapiBar
* @return array El Formulario
*/
function mapibar_admin() {
  $form = array();
  
  $form['contact'] = array(
      '#type' => 'fieldset',
      '#title' => t('Contact'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
  );
  
  $form['variables'] = array(
      '#type' => 'fieldset',
      '#title' => t('Settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
  );
  
  $form['languages'] = array(
      '#type' => 'fieldset',
      '#title' => t('Languages'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
  );
  
  $form['languages']['en'] = array(
      '#type' => 'fieldset',
      '#title' => t('English'),
      '#collapsible' => FALSE,
  );
  
  $form['languages']['br'] = array(
      '#type' => 'fieldset',
      '#title' => t('Portuguese'),
      '#collapsible' => FALSE,
  );
  
  $form['languages']['es'] = array(
      '#type' => 'fieldset',
      '#title' => t('Spanish'),
      '#collapsible' => FALSE,
  );
  
  // Contacto
  $form['contact']['mapibar_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mails'),
    '#default_value' => variable_get('mapibar_mail', MAPIBAR_MAIL),
    '#description' => t("Only two mails, separated by commas and no spaces."),
    '#required' => TRUE,
  );
  
  $form['contact']['mapibar_phones'] = array(
    '#type' => 'textfield',
    '#title' => t('Phones'),
    '#default_value' => variable_get('mapibar_phones', MAPIBAR_PHONES),
    '#description' => t("Only two phones, separated by commas and no spaces."),
    '#required' => TRUE,
  );
  
  // Variables
  $form['variables']['mapibar_chat'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Chat window'),
    '#size' => 60,
    '#default_value' => variable_get('mapibar_chat', MAPIBAR_CHAT),
    '#maxlength' => 300,
    '#required' => TRUE,
  );
  
  $form['variables']['mapibar_skype'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Skype window'),
    '#size' => 60,
    '#default_value' => variable_get('mapibar_skype', MAPIBAR_SKYPE),
    '#maxlength' => 300,
    '#required' => TRUE,
  );

  $form['variables']['mapibar_call'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for call free window'),
    '#size' => 60,
    '#default_value' => variable_get('mapibar_call', MAPIBAR_CALL),
    '#maxlength' => 300,
    '#required' => TRUE,
  );
  
  $form['variables']['mapibar_width'] = array(
    '#type' => 'textfield',
    '#title' => t('The bar width in px'),
    '#size' => 10,
    '#default_value' => variable_get('mapibar_width', MAPIBAR_WIDTH),
    '#maxlength' => 4,
    '#required' => TRUE,
  );
  
  // Idiomas
  $form['languages']['en']['mapibar_en_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for english site (Optional)'),
    '#default_value' => variable_get('mapibar_en_url', 'http://www.machupicchutravelagency.com'),
  );
  $form['languages']['en']['mapibar_en_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in english (Optional)'),
    '#default_value' => variable_get('mapibar_en_title', 'Travel to Machu Picchu'),
  );
  
  $form['languages']['br']['mapibar_br_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for portuguese site (Optional)'),
    '#default_value' => variable_get('mapibar_br_url', 'http://brasil.machupicchu.biz'),
  );
  $form['languages']['br']['mapibar_br_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in portuguese (Optional)'),
    '#default_value' => variable_get('mapibar_br_title', 'Pacotes a Machu Picchu'),
  );
  
  $form['languages']['es']['mapibar_es_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for spanish site (Optional)'),
    '#default_value' => variable_get('mapibar_es_url', 'http://www.machupicchu.biz'),
  );
  $form['languages']['es']['mapibar_es_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in spanish (Optional)'),
    '#default_value' => variable_get('mapibar_es_title', 'Tours a Machu Picchu'),
  );
  
  return system_settings_form($form);
} // function mapibar_admin()

/**
 * 
 * @param 
 *  type $var lo que se va a juntar
 * @return 
 *  string lo juntado
 */
function mapibar_joiner($var) {
    $var = str_replace(',', '<br />', $var);
    return $var;
}

/**
 * The bar
 */
function mapibar_page_build(&$page) {
	global $language;
        
	$output = sprintf('
		<div id="contact-bar"> 
		  <ul> 
			<li id="cb-chat"> 
			  <div>%s</div>
			</li> 
			<li id="cb-mail"> <span>%s</span><br />%s</li> 
			<li id="cb-call"> <span>%s</span><br />%s</li> 
			<li id="cb-skype">%s</li> 
			<li id="cb-langs" class="idiomas last">', 
                                t('Chat with us<br /> 24/7'), 
                                t('Book 24 hours'),
                                mapibar_joiner(variable_get('mapibar_mail', MAPIBAR_MAIL)),
                                t('Book 24 hours'),
                                mapibar_joiner(variable_get('mapibar_phones', MAPIBAR_PHONES)),
                                t('Call us for FREE<br /> NOW!'));
			
			switch($language->language) {
				case 'es':
					$output .= sprintf('<em class="ban_en"><a href="%s" title="%s">%s</a></em><br /> 
					<em class="ban_br"><a href="%s" title="%s">%s</a></em>',
                                                variable_get('mapibar_en_url', 'http://www.machupicchutravelagency.com/'),
                                                variable_get('mapibar_en_title'),
                                                t('English'),
                                                variable_get('mapibar_br_url', 'http://brasil.machupicchu.biz/'),
                                                variable_get('mapibar_br_title'),
                                                t('Portuguese'));
				break;
				case 'en':
                                        $output .= sprintf('<em class="ban_br"><a href="%s" title="%s">%s</a></em><br /> 
					<em class="ban_es"><a href="%s" title="%s">%s</a></em>',
                                                variable_get('mapibar_br_url', 'http://brasil.machupicchu.biz/'),
                                                variable_get('mapibar_br_title'),
                                                t('Portuguese'),
                                                variable_get('mapibar_es_url', 'http://www.machupicchu.biz/'),
                                                variable_get('mapibar_es_title'),
                                                t('Spanish'));
				break;
				default:
                                        $output .= sprintf('<em class="ban_en"><a href="%s" title="%s">%s</a></em><br /> 
					<em class="ban_es"><a href="%s" title="%s">%s</a></em>',
                                                variable_get('mapibar_en_url', 'http://www.machupicchutravelagency.com/'),
                                                variable_get('mapibar_en_title'),
                                                t('English'),
                                                variable_get('mapibar_es_url', 'http://www.machupicchu.biz/'),
                                                variable_get('mapibar_es_title'),
                                                t('Spanish'));
			}
			$output .= '</li> 
		  </ul> 
		</div>';
		
		$page['page_bottom']['mapibar'] = array(
			'#type' => 'markup',
			'#markup' => $output
		);
} // function mapibar_page_build()